EXTRA_DIST = sample.xml style.css *.xsl

## You must set DOCNAME
DOCNAME = sample

##
## To customize style, you must copy following files and customize them.
##
#HTML_STYLE = html.xsl
#PDF_STYLE = pdf.xsl

include /usr/share/docbook-env/common/Makefile.cmn
